# Generated by Django 4.0.1 on 2022-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productinfo_manufacturer_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_delevary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_delevered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_receive',
            field=models.BooleanField(default=False),
        ),
    ]
