# Generated by Django 4.0.1 on 2022-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinfo_device_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
