# Generated by Django 4.0.1 on 2022-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinfo_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='product_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
