# Generated by Django 4.0.1 on 2022-08-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userinfo_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInfo',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
